### ISSUE TITLE
Directory Rename with refactors

### ISSUE THREAD

**Issue by ahutchings** [jurassix/atom-refactoring-codemods#1]

**Comment by jurassix** [comment]
I have this branch, [directory-refactor-support](https://github.com/jurassix/atom-refactoring-codemods/tree/directory-refactor-support), that I'm tracking changes for this change in. It badly needs tests, a code review, and many refactors, but its a start.

It's a very big change so we probably want to close this out soon.

@ahutchings @spudly

**Comment by jurassix** [comment]
:boom: this is completed in v0.4.1 and released to apm
