### ISSUE TITLE
Coverage reports

### ISSUE THREAD

**Issue by ahutchings** [jurassix/atom-refactoring-codemods#28]
Coveralls seems popular. Anything else worth looking at?

cc @spudly @jurassix

**Comment by ahutchings** [comment]
Went with coveralls. Added the travis config and readme badge already - all that's left is to enable the service.

**Comment by ahutchings** [comment]
@jurassix Once this repo is enabled at https://coveralls.io this can be closed.

**Comment by jurassix** [comment]
done
